import OrdersListPage from '../orders/OrdersListPage.jsx';
import {
  FaClockRotateLeft,
  FaListCheck,
  FaHourglassStart,
  FaMoneyBillWave,
  FaHand,
  FaBoxOpen,
  FaCircleCheck,
  FaBox,
  FaCodeBranch,
  FaLayerGroup,
  FaFlag,
  FaTruckFast,
  FaTruck,
  FaRoad,
  FaClock,
  FaTriangleExclamation,
  FaRotateLeft,
  FaBoxArchive,
  FaBan,
  FaUserClock,
  FaTrash,
} from 'react-icons/fa6';

const OMS_TOP_TILES = [
  { id: 'last24h', label: 'LAST 24H', type: 'last24h', variant: 'primary', icon: <FaClockRotateLeft /> },
  { id: 'total', label: 'TOTAL', type: 'total', variant: 'info', icon: <FaListCheck /> },
  { id: 'pending', label: 'PENDING', statusKeys: ['pending'], variant: 'warning', icon: <FaHourglassStart /> },
  {
    id: 'pay_pending',
    label: 'PAY PENDING',
    statusKeys: ['pay_pending', 'pay pending'],
    variant: 'warning',
    icon: <FaMoneyBillWave />,
  },
  { id: 'on_hold', label: 'ON HOLD', statusKeys: ['on_hold', 'on hold'], variant: 'dark', icon: <FaHand /> },
  { id: 'no_stock', label: 'NO STOCK', statusKeys: ['no_stock', 'no stock'], variant: 'danger', icon: <FaBoxOpen /> },
  {
    id: 'confirmed',
    label: 'CONFIRMED',
    statusKeys: ['confirmed'],
    variant: 'success',
    icon: <FaCircleCheck />,
  },
  { id: 'packed', label: 'PACKED', statusKeys: ['packed'], variant: 'info', icon: <FaBox /> },
  { id: 'split', label: 'SPLIT', statusKeys: ['split'], variant: 'primary', icon: <FaCodeBranch /> },
  {
    id: 'combined',
    label: 'COMBINED',
    statusKeys: ['combined'],
    variant: 'success',
    icon: <FaLayerGroup />,
  },
  { id: 'claim', label: 'CLAIM', statusKeys: ['claim'], variant: 'danger', icon: <FaFlag /> },
  {
    id: 're_dispatch',
    label: 'RE-DISPATCH',
    statusKeys: ['re_dispatch', 're-dispatch', 're dispatch'],
    variant: 'warning',
    icon: <FaTruckFast />,
  },
  { id: 'dispatched', label: 'DISPATCHED', statusKeys: ['dispatched'], variant: 'info', icon: <FaTruck /> },
  {
    id: 'out_for_delivery',
    label: 'OUT FOR DELIVERY',
    statusKeys: ['out_for_delivery', 'out for delivery'],
    variant: 'success',
    icon: <FaRoad />,
  },
  { id: 'stuck_5_days', label: 'STUCK 5+ DAYS', statusKeys: ['stuck_5_days', 'stuck 5+ days'], variant: 'warning', icon: <FaClock /> },
  { id: 'issues', label: 'ISSUES', statusKeys: ['issues', 'issue'], variant: 'danger', icon: <FaTriangleExclamation /> },
  { id: 'returned', label: 'RETURNED', statusKeys: ['returned', 'return'], variant: 'success', icon: <FaRotateLeft /> },
  { id: 'rto_received', label: 'RTO RECEIVED', statusKeys: ['rto_received', 'rto received'], variant: 'dark', icon: <FaBoxArchive /> },
  { id: 'cancelled', label: 'CANCELLED', statusKeys: ['cancelled', 'canceled'], variant: 'danger', icon: <FaBan /> },
  { id: 'customer_query', label: 'CUSTOMER QUERY', statusKeys: ['customer_query', 'customer query'], variant: 'primary', icon: <FaUserClock /> },
  { id: 'deleted', label: 'DELETED', statusKeys: ['deleted'], variant: 'dark', icon: <FaTrash /> },
];

const OMS_PAGE_CONFIG = {
  permissionModule: 'oms',
  pageTitle: 'OMS',
  pageSubtitle: 'Order Management System',
  topSummaryName: 'OMS Dashboard',
  topTiles: OMS_TOP_TILES,
  idPrefix: 'oms',
  exportFilePrefix: 'oms',
  exportSheetTitle: 'OMS',
  exportPdfTitle: 'OMS (with line items)',
  showFetchSyncToolbar: true,
  showRowSyncButton: true,
  showIntegrationColumn: true,
};

const OMS = () => <OrdersListPage config={OMS_PAGE_CONFIG} />;

export default OMS;
